export namespace Constants {
    const MY_LAST_COORD: string;
    const MY_LAST_LANGUAGE: string;
    const MY_LAST_MAP_STYLE: string;
    const MY_LAST_TRAVEL_MODE: string;
    const MY_LAST_ROUTE_CRITERIA: string;
    const DIRECTION_LAYER_ID: string;
    const DIRECTION_ARROW_BODY_LAYER_ID: string;
    const DIRECTION_ARROW_HEAD_LAYER_ID: string;
    const DIRECTION_DASH_PATH_LAYER_ID: string;
    const ARROW_BORDER_COLOR: string;
    const PATH_PRIMARY_COLOR: string;
    const PATH_PRIMARY_BORDER_COLOR: string;
    const PATH_SECONDARY_COLOR: string;
    const PATH_SECONDARY_BORDER_COLOR: string;
    const DASH_PATH_COLOR: string;
    const MAP_OBJECT_LINES_LAYER_ID: string;
    const MAP_OBJECT_POLYGONS_LAYER_ID: string;
    const LINES_BUFFER_LAYER_ID: string;
    const POINTS_BUFFER_LAYER_ID: string;
    const GEOFENCE_LINES_BUFFER_LAYER_ID: string;
    const GEOFENCE_POINTS_BUFFER_LAYER_ID: string;
    const BLOCKADE_LINES_BUFFER_LAYER_ID: string;
    const BLOCKADE_POINTS_BUFFER_LAYER_ID: string;
    const DRAWING_MAP_OBJECT_LINE_LAYER_ID: string;
    const DRAWING_MAP_OBJECT_POLYGON_LAYER_ID: string;
    const DRAG_MAP_OBJECT_LINE_LAYER_ID: string;
    const MAP_OBJECT_MARKER_COLOR: string;
    const MAP_OBJECT_MARKER_SYMBOL: string;
    const MAP_OBJECT_LINE_COLOR: string;
    const MAP_OBJECT_LINE_OPACITY: number;
    const MAP_OBJECT_LINE_WIDTH: number;
    const MAP_OBJECT_POLYGON_COLOR: string;
    const MAP_OBJECT_GEOFENCE_POLYGON_COLOR: string;
    const MAP_OBJECT_POLYGON_OPACITY: number;
    const MAP_OBJECT_BLOCKADE_POLYGON_COLOR: string;
    const MAP_OBJECT_BLOCKADE_FLAGPOLE_COLOR: string;
    const MAP_OBJECT_BLOCKADE_POLYGON_OPACITY: number;
    const ADMINISTRATIVE_BOUNDARIES_LAYER_ID: string;
    const ADMINISTRATIVE_BOUNDARIES_POLYGON_OPACITY: number;
    const ADMINISTRATIVE_BOUNDARIES_POLYGON_COLOR: string;
    const ADMINISTRATIVE_BOUNDARIES_OUTLINE_COLOR: string;
    const ADMINISTRATIVE_BOUNDARIES_OUTLINE_WIDTH: number;
    const CIRCLE_SEARCH_NEAR_BY_LAYER_ID: string;
    const LEVEL_PROVINCE: number;
    const LEVEL_PROVINCE_TITLE: string;
    const TYPE_PROVINCE: string;
    const LEVEL_DISTRICT: number;
    const LEVEL_DISTRICT_TITLE: string;
    const TYPE_DISTRICT: string;
    const LEVEL_WARD: number;
    const LEVEL_WARD_TITLE: string;
    const TYPE_WARD: string;
    const LEVEL_VILLAGE: number;
    const LEVEL_VILLAGE_TITLE: string;
    const TYPE_PLACE_LIST_FAVORITE: number;
    const NAME_PLACE_LIST_FAVORITE: string;
    const TYPE_PLACE_LIST_WANT_GO: number;
    const NAME_PLACE_LIST_WANT_GO: string;
    const TYPE_PLACE_LIST_STAR: number;
    const NAME_PLACE_LIST_STAR: string;
    const MY_PLACES_SHOW_HIDE_MARKER: string;
    const UNKNOWN_LOCATION: string;
    const MEASURE_LINE_LAYER_ID: string;
    const MEASURE_DRAWING_LINES_LAYER_ID: string;
    const MEASURE_DRAWING_LINE_OPACITY: number;
    const MEASURE_DRAG_LINE_LAYER_ID: string;
    const MEASURE_LINE_COLOR: string;
    const MEASURE_LINE_WIDTH: number;
    const BARRIER_ID_TEST: string;
    const GET_VIRTUAL_ROUTE_ID: string;
    const INCIDENT_PATH_PRIMARY_COLOR: string;
    const INCIDENT_PATH_PRIMARY_BORDER_COLOR: string;
    const INCIDENT_DIRECTION_LAYER_ID: string;
    const INCIDENT_DIRECTION_DASH_PATH_LAYER_ID: string;
    namespace MAP_OBJECT {
        const POINTER: number;
        const MARKER: number;
        const LINES: number;
        const POLYGON: number;
        const PATH: number;
    }
    const LABEL_FONTSIZE: number;
    const COLORS: string[][];
    const POPULAR_ICONS: string[][];
    const INACTIVE_USER_TIMEOUT: number;
    const DEFAULT_IMAGE_ICON_SIZE: number;
    const DEFAULT_VIDEO_MARKER_ICON: string;
    const DEFAULT_IMAGE_MARKER_ICON: string;
    namespace KEYS {
        const ESC: number;
        const TAB: number;
        const RETURN: number;
        const LEFT: number;
        const UP: number;
        const RIGHT: number;
        const DOWN: number;
        const ENTER: number;
    }
    const PLATE_DETECTION_HISTORY_VIRTUAL_ROUTE_LAYER_ID: string;
    const FACE_DETECTION_HISTORY_VIRTUAL_ROUTE_LAYER_ID: string;
    const WHAT_HERE_POPUP_ID: string;
    const CAMERA_MONITORING_LAYER_ID: string;
    namespace CAMERA_STATUS_COLOR {
        const BAD: string;
        const BROKEN: string;
        const GOOD: string;
    }
    namespace CAMERA_STATUS {
        export const NO_DATA: number;
        const GOOD_1: number;
        export { GOOD_1 as GOOD };
        const BROKEN_1: number;
        export { BROKEN_1 as BROKEN };
    }
}
//# sourceMappingURL=Constants.d.ts.map